import { ScrollView , AboutSlint, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { ClosureStudioLogoStacked } from "../components/closure-studio-logo.slint";
import { FontGlobals } from "../font-globals.slint";

export component AboutPage {
    VerticalLayout {
        VerticalBox {
            alignment: center;

            ClosureStudioLogoStacked {
                single-row-size: 60px;
            }

            Text {
                font-family: FontGlobals.alphanumeric-text-sans;
                font-size: 16px;
                vertical-alignment: top;
                horizontal-alignment: center;

                text: "可露希尔轻量级桌面客户端-D32钢\n2024 Closure Studio\n<github.com/closure-studio>";
            }
        }

        HorizontalBox {
            alignment: center;
            spacing: 24px;
            height: 128px;

            VerticalLayout {
                spacing: 5px;
                alignment: center;

                HorizontalLayout {
                    alignment: center;

                    Rectangle {
                        width: 72px;
                        height: 72px;
    
                        clip: true;
                        border-radius: 10px;
                        Image {
                            source: @image-url("../images/closure_logo_ferris.png");
    
                            width: 72px;
                            height: 72px;
                        }
                    }
                }
            }

            AboutSlint {
                width: 128px;
            }
        }
    }
}