import { ScrollView , AboutSlint, HorizontalBox, VerticalBox, StyleMetrics } from "std-widgets.slint";
import { ClosureStudioLogoStacked } from "../components/closure-studio-logo.slint";
import { FontGlobals } from "../font-globals.slint";

export component AboutPage {
    ScrollView {
        VerticalBox {
            alignment: start;
            spacing: 24px;

            HorizontalBox {
                spacing: 24px;

                ClosureStudioLogoStacked {
                    single-row-size: 60px;
                }
            }

            HorizontalBox {
                alignment: center;
                spacing: 24px;

                VerticalLayout {
                    alignment: space-around;

                    Rectangle {
                        width: 72px;
                        height: 72px;
    
                        clip: true;
                        border-radius: 15px;
                        Image {
                            source: @image-url("../images/closure_logo_ferris.png");
    
                            width: 72px;
                            height: 72px;
                        }
                    }
                }

                Text {
                    font-family: FontGlobals.alphanumeric-text-sans;
                    font-size: 16px;
                    vertical-alignment: center;
                    horizontal-alignment: left;
    
                    text: "(c) 2023 Closure Studio <github.com/closure-studio>";
                }

                AboutSlint {
                    width: 128px;
                }
            }

            HorizontalBox {
                alignment: center;
                spacing: 24px;
            }
        }
    }
}