import { GridBox , Button, HorizontalBox, VerticalBox, StyleMetrics} from "std-widgets.slint";
import { GameInfo, GameState } from "../game-info.slint";
import { GameStatusBadge } from "game-status-badge.slint";

export component GameCardDoctorInfo inherits Rectangle {
    in property <GameInfo> info;

    VerticalLayout {
        alignment: start;

        HorizontalBox {
            alignment: space-between;

            VerticalLayout {
                alignment: start;

                Rectangle {
                    doctor-name := Text {
                        text: info.doctor-name;
                        font-size: 36px;
                    }
                    border-radius: self.width * 0.05;
    
                    max-width: 120px;
                    max-height: 40px;
                }
    
                doctor-serial := Text {
                    text: info.doctor-serial;
                    font-size: 18px;
                    font-italic: true;
                    color: StyleMetrics.default-text-color.transparentize(60%);
    
                    vertical-alignment: bottom;
                }
            }

            GameStatusBadge {
                info: info;
            }
        }

        GridBox {
            Text { text: @tr("理智：") + info.ap; font-size: 14px; row: 0; col: 0; }
            Text { text: @tr("作战关卡：") + info.battle-map; font-size: 14px; row: 1; col: 0; }
            Text { text: @tr("可露希尔当前为技术预览版本，停止游戏功能和更改游戏设置功能暂不可用，感谢您的理解和耐心等待。"); font-size: 14px; row: 2; col: 0; }
        }
        
        min-width: 150px;
    }
}