import { GridBox , Button, HorizontalBox, VerticalBox, StyleMetrics , Spinner} from "std-widgets.slint";
import { GameInfo, GameState, GameOperationRequestState } from "../game-info.slint";

enum ButtonType {
    StartGame,
    StopGame,
    RestartGame
}

global GameOperationUtil {
    public pure function is-busy(info: GameInfo) -> bool {
        info.request-state == GameOperationRequestState.Requesting
            || info.game-state == GameState.Logging
            || info.game-state == GameState.Captcha
    }

    public pure function can-login(info: GameInfo) -> bool {
        if is-busy(info) {
            return false;
        }

        info.game-state == GameState.Faulted || info.game-state == GameState.Stopped
    }

    public pure function can-interrupt(info: GameInfo) -> bool {
        if is-busy(info) {
            return false;
        }

        info.game-state == GameState.Running
    }
}

component GameOperationShortcutButton inherits Button {
    in property <ButtonType> type;
    in property <GameInfo> info;

    enabled: 
        (type == ButtonType.StartGame && GameOperationUtil.can-login(info))
        || (type == ButtonType.StopGame && GameOperationUtil.can-interrupt(info))
        || (type == ButtonType.RestartGame && GameOperationUtil.can-interrupt(info));
}

component StartGameButton inherits GameOperationShortcutButton {
    in property <bool> compact: false;

    type: ButtonType.StartGame;
    primary: true;
    icon: StyleMetrics.dark-color-scheme // primary Button 的文字颜色与默认文字颜色相反
        ? @image-url("../images/game_card_shortcut_start_light.svg")
        : @image-url("../images/game_card_shortcut_start.svg");
    text: !compact 
        ? @tr("启动") 
        : "";
}

component StopGameButton inherits GameOperationShortcutButton {
    in property <bool> compact: false;

    type: ButtonType.StopGame;
    icon: StyleMetrics.dark-color-scheme 
        ? @image-url("../images/game_card_shortcut_stop.svg")
        : @image-url("../images/game_card_shortcut_stop_light.svg");
    text: !compact 
        ? @tr("停止") 
        : "";
}

// component RestartGameButton inherits GameOperationShortcutButton {
//     in property <bool> compact: false;
//    
//     type: ButtonType.RestartGame;
//     icon: StyleMetrics.dark-color-scheme 
//         ? @image-url("../images/game_card_shortcut_restart.svg")
//         : @image-url("../images/game_card_shortcut_restart_light.svg");
//     text: !compact 
//         ? @tr("重启") 
//         : "";
// }

export component GameCardOperationShortcutPanel inherits HorizontalLayout {
    in property <GameInfo> info;

    in property <bool> compact: false;

    callback start-game(string /* GameInfo ID */ );
    callback stop-game(string /* GameInfo ID */ );
    callback restart-game(string /* GameInfo ID */ );
    
    spacing: 10px;

    StartGameButton {
        info: info;
        compact: compact;
        clicked => { start-game(info.id); }
    }

    StopGameButton {
        info: info;
        compact: compact;
        clicked => { stop-game(info.id); }
    }

    // RestartGameButton {
    //     info: info;
    //     compact: compact;
    //     clicked => { restart-game(info.id); }
    // }

    // request-spinner := Spinner {
    //     width: self.visible ? root.height : 0px;
    //     indeterminate: true;
    //     visible: info.request-state == GameOperationRequestState.Requesting;
    // }
}

export component GameCardOperationShortcutPanelVertical inherits VerticalLayout {
    in property <GameInfo> info;

    in property <bool> compact: false;

    callback start-game(string /* GameInfo ID */ );
    callback stop-game(string /* GameInfo ID */ );
    callback restart-game(string /* GameInfo ID */ );
    
    spacing: 10px;
    alignment: start;

    if GameOperationUtil.can-login(info): StartGameButton {
        info: info;
        compact: compact;
        clicked => { start-game(info.id); }
    }

    if GameOperationUtil.can-interrupt(info): StopGameButton {
        info: info;
        compact: compact;
        clicked => { stop-game(info.id); }
    }

    // RestartGameButton {
    //     info: info;
    //     compact: compact;
    //     clicked => { restart-game(info.id); }
    // }
}