import { Palette, HorizontalBox, Button, GroupBox } from "std-widgets.slint";
import { GameInfo, BattleMap, GameOptionSaveState, BattleUpdateFields } from "../game-info.slint";

export component GameCardBattle inherits HorizontalLayout {
    in property <GameInfo> info;
    
    callback select-map();

    alignment: center;

    VerticalLayout {
        GroupBox {
            HorizontalBox {
                Button {
                    text: @tr("选择作战关卡…");
                    clicked => { select-map(); }
                }
            }
        }

        width: clamp(root.width - 20px, 300px, 1000px);
    }
}
