import { GameInfo, GameState, GameLogLoadState, GameLogLoadRequestType, GameInfoViewType, GameOptions } from "../game-info.slint";
import { Callbacks } from "../callbacks.slint";
import { GameCard } from "game-card.slint";
import { ScrollView , VerticalBox} from "std-widgets.slint";

export component GameInfoPage {
    in property <[GameInfo]> game-info-list;

    ScrollView {
        VerticalBox {
            alignment: start;

            for game-info in game-info-list: GameCard {
                info: game-info;

                start-game(id) => { Callbacks.start-game(id); }
                stop-game(id) => { Callbacks.stop-game(id); }
                restart-game(id) => { Callbacks.restart-game(id); }
                save-options(id, options) => { Callbacks.save-options(id, options); }
                load-logs(id, type) => { Callbacks.load-logs(id, type); }
                view-changed(id, type) => { Callbacks.view-changed(id, type); }
            }
        }
    }
}