import { GameInfo, GameState, GameLogLoadState, GameLogLoadRequestType, GameInfoViewType } from "../game-info.slint";
import { GameCard } from "game-card.slint";
import { ScrollView , VerticalBox} from "std-widgets.slint";

export component GameInfoPage {
    callback start-game(string);
    callback stop-game(string);
    callback restart-game(string);
    callback save-options(string);
    callback load-logs(string, GameLogLoadRequestType);
    callback view-changed(string, GameInfoViewType);

    in property <[GameInfo]> game-info-list;

    ScrollView {
        VerticalBox {
            for game-info in game-info-list: GameCard {
                info: game-info;

                start-game(id) => { start-game(id); }
                stop-game(id) => { stop-game(id); }
                restart-game(id) => { restart-game(id); }
                save-options(id) => { save-options(id); }
                load-logs(id, type) => { load-logs(id, type); }
                view-changed(id, type) => { view-changed(id, type); }
            }
        }
    }
}