import { GridBox , Button, HorizontalBox, VerticalBox, StyleMetrics} from "std-widgets.slint";
import { GameInfo, GameState } from "../game-info.slint";

component GameStatusBadgeBase inherits Rectangle {
    in property <GameInfo> info;

    out property <brush> status-color;
    out property <string> status-text;
    out property <image> status-icon;

    states [
        logging when info.game-state == GameState.Logging: {
            status-color: @linear-gradient(15deg, #32b1d4 0%, #1299be 100%);
            status-text: @tr("登录中");
            status-icon: @image-url("../images/game_status_logging.svg");
        }
        running when info.game-state == GameState.Running: {
            status-color: @linear-gradient(15deg, #59b72a 0%, #5db813 100%);
            status-text: @tr("运行中");
            status-icon: @image-url("../images/game_status_running.svg");
        }
        faulted when info.game-state == GameState.Faulted: {
            status-color: @linear-gradient(15deg, #dd4f24 0%, #db4321 100%);
            status-text: info.status-text;
            status-icon: @image-url("../images/game_status_faulted.svg");
        }
        stopped when info.game-state == GameState.Stopped: {
            status-color: #494949;
            status-text: @tr("已停止");
            status-icon: @image-url("../images/game_status_stopped.svg");
        }
        captcha when info.game-state == GameState.Captcha: {
            status-color: @linear-gradient(15deg, #32b1d4 0%, #1299be 100%);
            status-text: @tr("需要人机验证");
            status-icon: @image-url("../images/game_status_captcha.svg");
        }
    ]
}

export component GameStatusBadge inherits GameStatusBadgeBase {
    in property <bool> compact;
    private property <length> horz-padding: compact
        ? 0px
        : 15px;

    border-color: self.status-color;
    border-radius: self.height * 0.25;
    border-width: self.height * 0.08;

    animate background { duration: 200ms; }

    HorizontalBox {
        alignment: space-around;
        padding-left: horz-padding;
        padding-right: horz-padding;
        spacing: 15px;

        Image {
            source: root.status-icon;
            colorize: StyleMetrics.default-text-color;
            width: 24px;
            height: 24px;
        }

        if !compact : Text {
            text: root.status-text;
            font-size: 14px;
            horizontal-alignment: center;
            vertical-alignment: center;
            min-width: 96px;
        }
    }
}

export component GameStatusBadgeWide inherits GameStatusBadgeBase {
    border-radius: 4px;
    border-width: 1px;
    border-color: StyleMetrics.default-text-color.transparentize(30%);
    clip: true;

    HorizontalBox {
        padding-left: 15px;
        padding-right: 15px;
        spacing: 15px;

        Image {
            source: root.status-icon;
            colorize: StyleMetrics.default-text-color;
            width: 26px;
            height: 26px;

            horizontal-stretch: 0;
        }

        Text {
            text: root.status-text;
            font-size: 14px;
            horizontal-alignment: center;
            vertical-alignment: center;

            horizontal-stretch: 1;
        }
    }
}