import { Palette, HorizontalBox } from "std-widgets.slint";
import { FontGlobals } from "../font-globals.slint";

export component ClosureStudioLogoSingleRow inherits HorizontalBox {
    in property <length> single-row-size: 48px;
    in property <image> logo: @image-url("../images/closure_drone.png");
    in property <bool> compact: false;
    alignment: space-around;
    
    VerticalLayout {
        alignment: start;

        HorizontalLayout {
            alignment: start;
            spacing: single-row-size * 10%;
    
            VerticalLayout {
                alignment: center;
    
                Image {
                    source: logo;
    
                    width: single-row-size;
                    height: single-row-size;
                }
            }
    
            if !compact: Text {
                font-family: FontGlobals.closure-studio-logo;
                font-size: single-row-size * 85%;
                height: single-row-size;
                text: "CLOSURE STUDIO";
                color: Palette.alternate-foreground;
                vertical-alignment: center;
            }
        }
    }
}

export component ClosureStudioLogoStacked inherits HorizontalBox {
    in property <length> single-row-size: 64px;
    in property <image> logo: @image-url("../images/closure_drone.png");
    alignment: space-around;

    VerticalLayout {
        alignment: start;

        Text {
            font-family: FontGlobals.closure-studio-logo;
            font-size: single-row-size * 90%;
            height: single-row-size;
            text: "CLOSURE";
            color: Palette.alternate-foreground;
            vertical-alignment: center;
        }

        HorizontalLayout {
            alignment: start;
            spacing: 3px;

            Text {
                font-family: FontGlobals.closure-studio-logo;
                font-size: single-row-size * 90%;
                height: single-row-size;
                text: "STUDIO";
                color: Palette.alternate-foreground;
                vertical-alignment: center;
            }

            VerticalLayout {
                alignment: start;

                Image {
                    source: logo;
    
                    width: single-row-size * 90%;
                    height: single-row-size * 90%;
                }
            }
        }
    }
}

export component DesktopEditionIcon inherits HorizontalLayout {
    padding: 5px;
    alignment: space-around;

    Rectangle {
        height: 22px;
        width: 140px;
        border-radius: 8px;

        HorizontalLayout {
            padding-left: 5px;
            padding-right: 5px;
            alignment: space-around;

            Text {
                font-size: 15px;
                font-family: FontGlobals.closure-studio-logo;
                color: Palette.alternate-foreground.transparentize(20%);
                text: "D32 ";
                vertical-alignment: center;
            }

            VerticalLayout {
                alignment: center;
                
                Rectangle {
                    Image {
                        source: @image-url("../images/D32_Steel.png");
                        
                        width: 36px;
                        height: 36px;
                    }

                    width: 32px;
                    height: 18px;
                }
            }

            Text {
                font-size: 15px;
                font-family: FontGlobals.closure-studio-logo;
                color: Palette.alternate-foreground.transparentize(20%);
                text: " EDITION";
                vertical-alignment: center;
            }
        }

        background: Palette.control-background.transparentize(50%);
    }
}