import { Palette } from "std-widgets.slint";

export component LoadingPlaceholder inherits Rectangle {
    in property <bool> loading: true;

    pure function get-flash-ratio-unclamped() -> float {
        Math.mod(animation-tick(), 1.5s) / 1s * 150% - 25%
    }

    pure function get-flash-ratio() -> float {
        Math.clamp(get-flash-ratio-unclamped(), 0%, 100%);
    }

    pure function get-flash-left-ratio() -> float {
        Math.clamp(get-flash-ratio-unclamped() - 25%, 0%, 100%);
    }

    pure function get-flash-right-ratio() -> float {
        Math.clamp(get-flash-ratio-unclamped() + 25%, 0%, 100%);
    }

    pure function get-gradient(angle: angle) -> brush {
        @linear-gradient(angle, 
            #fff0 get-flash-left-ratio(), 
            Palette.foreground.transparentize(90%) get-flash-ratio(), 
            #fff0 get-flash-right-ratio())
    }

    background: loading 
        ? get-gradient(150deg)
        : #fff0;
}