[workspace]
members = ["arkhost_api"]

[package]
name = "arkhost-ui-slint"
version = "0.1.0"
authors = ["WG <wg138940@outlook.com>"]
edition = "2021"
build = "build.rs"
public = false

[features]
default = ["desktop-app"]
desktop-app = ["dep:winit", "dep:ipc-channel", "dep:subprocess", "dep:argh"]

[dependencies]
slint = "1.3.2"
webbrowser = "0.8"
arkhost-api = { path = "arkhost_api" }
tokio = { version = "1.34.0", features = ["full"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
wry = "0.35.0"
winit = { version = "0.29", features = ["rwh_05"], optional = true }
ipc-channel = { version = "0.18.0", features = ["async"], optional = true }
subprocess = { version = "0.2.9", optional = true }
argh = { version = "0.1.12", optional = true }
anyhow = "1.0.75"
thiserror = "1.0.50"
home = "0.5.5"
futures-util = "0.3.29"
async-trait = "0.1.74"
reqwest = "0.11.22"
reqwest-middleware = "0.2.4"
reqwest-retry = "0.3.0"
http-cache = { version = "0.17.0", features = [
    "manager-cacache",
    "cacache-tokio",
], default-features = false }
http-cache-reqwest = "0.12.0"
image = { version = "0.24.7", features = ["webp"], default-features = false }
bytes = "1.5.0"

[build-dependencies]
slint-build = "1.3.2"
embed-resource = "2.4"
