import { Button, VerticalBox , HorizontalBox , TabWidget } from "std-widgets.slint";
import { GameInfo } from "game-info.slint";
import { LoginWindow, LoginState } from "login-window.slint";
import { GameInfoPage, FetchGamesState } from "pages/game-info-page.slint";
import { AboutPage } from "pages/about-page.slint";
import { Callbacks } from "callbacks.slint";
import { ClosureStudioLogoSingleRow } from "components/closure-studio-logo.slint";

export component AppWindow inherits Window {
    title: @tr("Closure Studio");
    icon: @image-url("images/closure_drone.png");

    in property <[GameInfo]> game-info-list;
    in property <FetchGamesState> fetch-games-state;
    in-out property <LoginState> login-state;
    in-out property <string> login-status-text;

    callback login-requested <=> login-window.login-requested;
    callback auth-requested <=> login-window.auth-requested;
    callback register-requested <=> login-window.register-requested;
    callback open-ext-link(string);

    public function set-use-auth(account: string, use-auth-val: bool) {
        login-window.set-use-auth(account, use-auth-val);
    }

    callback start-game <=> Callbacks.start-game;
    callback stop-game <=> Callbacks.stop-game;
    callback restart-game <=> Callbacks.restart-game;
    callback save-options <=> Callbacks.save-options;
    callback load-logs <=> Callbacks.load-logs;
    callback view-changed <=> Callbacks.view-changed;

    preferred-width: 1280px;
    preferred-height: 720px;

    VerticalLayout {
        visible: login-state == LoginState.Logged;

        TabWidget {
            Tab {
                title: @tr("账号管理");
    
                VerticalLayout {
                    game-info-page := GameInfoPage {
                        game-info-list: game-info-list;
                        fetch-games-state: fetch-games-state;
                    }
                }
            }
    
            Tab {
                title: @tr("关于");
    
                VerticalLayout {
                    AboutPage {
                        
                    }
                }
            }
        }
    }

    login-window := LoginWindow {
        visible: login-state != LoginState.Logged;
        login-state: login-state;
        login-status-text: login-status-text;
    }
}
