import { Button, VerticalBox, HorizontalBox, TabWidget, StyleMetrics } from "std-widgets.slint";
import { GameInfo } from "game-info.slint";
import { SlotInfo } from "slot-info.slint";
import { UserInfo } from "user-info.slint";
import { LoginWindow, LoginState } from "login-window.slint";
import { GameInfoPage, FetchGamesState, SseConnectState } from "pages/game-info-page.slint";
import { AboutPage } from "pages/about-page.slint";
import { Callbacks } from "callbacks.slint";
import { ClosureStudioLogoSingleRow } from "components/closure-studio-logo.slint";
import { SlotPage } from "pages/slot-page.slint";
import { FontGlobals } from "font-globals.slint";

export component AppWindow inherits Window {
    title: @tr("Closure Studio");
    icon: @image-url("images/closure_drone.png");

    in property <[GameInfo]> game-info-list;
    in property <FetchGamesState> fetch-games-state;
    in property <SseConnectState> sse-connect-state;
    in property <[SlotInfo]> slot-info-list;
    in property <UserInfo> user-info;
    in property <string> selected-slot;
    in-out property <LoginState> login-state;
    in-out property <string> login-status-text;

    callback login-requested <=> login-window.login-requested;
    callback auth-requested <=> login-window.auth-requested;
    callback register-requested <=> login-window.register-requested;

    callback start-game <=> Callbacks.start-game;
    callback stop-game <=> Callbacks.stop-game;
    callback restart-game <=> Callbacks.restart-game;
    callback save-options <=> Callbacks.save-options;
    callback load-logs <=> Callbacks.load-logs;
    callback view-changed <=> Callbacks.view-changed;
    callback reconnect-sse <=> Callbacks.reconnect-sse;

    callback refresh-user-info <=> Callbacks.refresh-user-info;
    callback refresh-slot-info <=> Callbacks.refresh-slot-info;
    callback submit-sms-verify-code <=> Callbacks.submit-sms-verify-code;
    callback fetch-qq-verify-code <=> Callbacks.fetch-qq-verify-code;

    callback slot-selected <=> Callbacks.slot-selected;
    callback expand-verify-slot <=> Callbacks.expand-verify-slot;
    callback update-slot <=> Callbacks.update-slot;
    callback reset-slot-update-request-state <=> Callbacks.reset-slot-update-request-state;
    
    callback open-ext-link <=> Callbacks.open-ext-link;
    callback return-to-login-page <=> Callbacks.return-to-login-page;

    public function set-use-auth(account: string, use-auth-val: bool) {
        login-window.set-use-auth(account, use-auth-val);
    }

    public function do-return-to-login-page() {
        login-state = LoginState.Unlogged;
        login-status-text = "";
    }

    preferred-width: 1280px;
    preferred-height: 800px;
    default-font-weight: 350;

    background: StyleMetrics.dark-color-scheme
        ? StyleMetrics.window-background
        : StyleMetrics.window-background.darker(5%);

    VerticalLayout {
        visible: login-state == LoginState.Logged;

        page-tab := TabWidget {
            Tab {
                title: @tr("Dashboard");
    
                VerticalLayout {
                    game-info-page := GameInfoPage {
                        user: user-info;
                        game-info-list: game-info-list;
                        fetch-games-state: fetch-games-state;
                        sse-connect-state: sse-connect-state;

                        goto-slot-page => { page-tab.current-index = 1; }
                    }
                }
            }

            Tab {
                title: @tr("账号管理");

                VerticalLayout {
                    slot-page := SlotPage {
                        slot-info-list: slot-info-list;
                        selected-slot: selected-slot;
                        user-info: user-info;
                    }
                }
            }

            Tab {
                title: @tr("关于");
    
                VerticalLayout {
                    AboutPage {
                        
                    }
                }
            }
        }
    }

    login-window := LoginWindow {
        visible: login-state != LoginState.Logged;
        login-state: login-state;
        login-status-text: login-status-text;
    }
}
