import { GameInfo, GameState, GameLogLoadState, GameLogLoadRequestType, GameInfoViewType, GameOptions, BattleMap, BattleUpdateFields } from "game-info.slint";
import { SlotUpdateDraft, SlotUpdateRequestState } from "slot-info.slint";

export global Callbacks {
    callback start-game(string);
    callback stop-game(string);
    callback restart-game(string);
    callback save-options(string, GameOptions);
    callback load-logs(string, GameLogLoadRequestType);
    callback view-changed(string, GameInfoViewType);
    callback reconnect-sse();
    callback search-maps(string, string, bool);
    callback set-map-selected(string, BattleMap, bool);
    callback reset-selected-maps(string);
    callback save-maps(string, BattleUpdateFields);

    callback refresh-user-info();
    callback refresh-slot-info();
    callback submit-sms-verify-code(string);
    callback fetch-qq-verify-code();

    callback slot-selected(string);
    callback expand-verify-slot();
    callback update-slot(string, SlotUpdateDraft);
    callback reset-slot-update-request-state(string);

    callback open-ext-link(string);
    callback return-to-login-page();
}