import "fonts/Raleway-Bold.ttf";
import "fonts/RethinkSans-VariableFont_wght.ttf";
import "fonts/SignusDigitalRoundNbp.ttf";

export global FontGlobals {
    in-out property <string> closure-studio-logo: "Raleway";
    in-out property <string> alphanumeric-text-sans: "Rethink Sans";
    in-out property <string> dotted: "Signus Digital Round NBP";
    // CJK字体会显著增大打包大小和内存占用，所以使用系统默认

    in-out property <int> emphasis-font-weight: 385;
}