export enum GameState {
    Logging,
    Running,
    Faulted,
    Stopped,
    Captcha
}

export enum GameOperationRequestState {
    Idle,
    Requesting
}

export enum GameLogLoadState {
    NotLoaded,
    Loading,
    Loaded,
}

export enum GameLogLoadRequestType {
    Later,
    Former
}

export enum BattleScreenshotsLoadState {
    Idle,
    Loading
}

export struct GameLogEntry {
    timestamp: string,
    attributes: string,
    content: string,
}

export enum GameOptionSaveState {
    Idle,
    Saving
}

export struct GameOptions {
    battle-maps: [string],
    enable-building-arrange: bool,
    enable-auto-battle: bool,
    ap-reserve: int,
    recruit-ignore-robot: bool,
    recruit-reserve: int,
    accelerate-slot-cn: string,
}

export enum GameInfoViewType {
    DoctorInfo,
    Battle,
    Details,
    Settings,
    Logs,
}

export struct AvatarInfo {
    loaded: bool,
    avatar-image: image}

export struct IllustInfo {
    loaded: bool,
    illust-image: image,
    pivot-factor-x: float,
    pivot-factor-y: float,
    offset-x: float,
    offset-y: float,
    scale-x: float,
    scale-y: float,
    size-x: float,
    size-y: float,
}

export struct BattleMap {
    map-id: string,
    code-name: string,
    display-name: string,
}

export struct BattleUpdateFields {
    maps: [BattleMap],
}

export struct GameDetails {  
    loaded: bool,
    avatar: AvatarInfo,
    char-illust: IllustInfo,
    diamond: string,
    diamond-shard: string,
    gacha-ticket: string,
    tenfold-gacha-ticket: string,
    gold: string,
    max-ap: string,
    recruit-license: string,
    secretary: string,
    social-point: string,
}

export struct GameInfo {
    id: string,
    doctor-name: string,
    doctor-level: string,
    doctor-serial: string,
    status-text: string,
    ap: string,
    battle-map: string,
    game-state: GameState,
    options: GameOptions,
    log-loaded: GameLogLoadState,
    logs: [GameLogEntry],
    request-state: GameOperationRequestState,
    save-state: GameOptionSaveState,
    active-view: GameInfoViewType,
    details: GameDetails,
    map-search-results: [BattleMap],
    selected-maps: [BattleMap],
    battle-screenshots: [image],
    current-battle-screenshot-series: string,
    remote-battle-screenshot-series: string,
    battle-screenshots-loading: BattleScreenshotsLoadState,
}

export global GameModels {
    out property <[string]> accelerate-slot-cn: [
        "顶层左",
        "顶层中",
        "顶层右",
        "中层左",
        "中层中",
        "中层右",
        "底层左",
        "底层中",
        "底层右",
    ];
}
