import { GameInfo, GameState, GameLogLoadState, GameLogLoadRequestType, GameInfoViewType, GameOptions } from "game-info.slint";
import { SlotInfo, SlotState, SlotUpdateRequestState, SlotUpdateDraftType, SlotPlatform, SlotDetailsViewState } from "slot-info.slint";
import { UserInfo, UserStatus, UserTier, UserProgress} from "user-info.slint";
import { GachaGroup } from "gacha-info.slint";

export global MockData {
    out property <GameInfo> game-info: {
        id: "test",
        doctor-name: "Dr. Nonary",
        doctor-level: "120",
        doctor-serial: "G199------88",
        status-text: "",
        ap: "135",
        battle-map: "1-7",
        game-state: GameState.Stopped,
        options: {

        },
        log-loaded: GameLogLoadState.Loaded,
        logs: [
            { timestamp: "12-20.18:52:59", content: "作战成功 " },
            { timestamp: "12-20.18:52:58", content: "正在进攻1-7 " },
            { timestamp: "12-20.18:52:57", content: "很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长 " },
            { timestamp: "12-20.18:52:57", content: "very very very very very very very very very very very very very very very very very long " },
            { timestamp: "12-20.18:52:56", content: "一二三四五六七八九十\n换行\n1234567890Alphanumeric\nEmoji：“🤔” " },
            { timestamp: "12-20.18:52:55", content: "下面是空字符串 " },
            { timestamp: "12-20.18:52:54", content: "" },
            { timestamp: "12-20.18:52:53", content: "上面是空字符串 " },
        ],
        details: {
            loaded: true,
            diamond: "233",
            diamond-shard: "180000",
            gacha-ticket: "300",
            tenfold-gacha-ticket: "30",
            gold: "368880000",
            max-ap: "135",
            recruit-license: "1000",
            secretary: "澄闪",
            social-point: "300"
        },
        selected-maps: [
            { code-name: "1-7", display-name: "暴君" },
            { code-name: "", display-name: "main_01-07" },
        ],
        map-search-results: [
            { code-name: "1-7", display-name: "暴君" },
            { code-name: "HS-114514", display-name: "海猫公子种地（危机磨难险境突袭剿灭紧急作战）" }
        ]
    };

    out property <SlotInfo> slot-info: {
        uuid: "00000000-0000-0000-0000-000000000000",
        state: SlotState.Synchronized,
        // game-account: "13344445555",
        // game-account-split: ["13344445555", ""],
        game-account: "LeaderOne@rhodes-island.org",
        game-account-split: ["LeaderOne", "@rhodes-island.org"],
        platform: SlotPlatform.Official,
        description: "可露希尔托管凭证 · 基础型",
        view-state: SlotDetailsViewState.Independent,
        verify-rules: [
            {
                has-result: true,
                fulfilled: false,
                description: "仅限添加归属认证手机号",
                status-text: "无法绑定验证账号（接受过本平台短信的手机号“19988887777”）以外的账号到该账号位"
            },
            {
                has-result: true,
                fulfilled: true,
                description: "仅限添加手机号账号",
                status-text: "已通过验证"
            }
        ],
        last-verify: {
            update-type: SlotUpdateDraftType.Update,
            game-account: "18877776666",
            platform: SlotPlatform.Bilibili,
            password: "secret"
        },
    };

    out property <UserInfo> user-info: {
        nickname: "doctor@rhodes-island.org",
        status: UserStatus.Normal,
        tier: UserTier.QQVerified,
        progress: UserProgress.QQVerified,
        phone: "12345",
        qq: "67890",
        qq-verify-code-cached: "verifyCode:kfc-crazy-thursday-v-me-50"
    };

    out property <[GachaGroup]> gacha-recrods: [
        {
            pool-name: "限定卡池“何以为我”每日一抽",
            pulls: [
                { doc-name: "Actor", rarity: "6★", character-avatar: @image-url("images/D32_Steel.png") },
                { doc-name: "Boctor", rarity: "5★", character-avatar: @image-url("images/icon_ap.png") },
                { doc-name: "Coctor", rarity: "4★", character-avatar: @image-url("images/closure_logo_ferris.png") },
                { doc-name: "Doctor", rarity: "6★" },
                { doc-name: "一二三四五六七八", rarity: "限定", character-avatar: @image-url("images/closure_drone.png") },
                { doc-name: "一二三四五六七八九", rarity: "2★" },
            ]
        }, {
            pool-name: "公开招募",
            pulls: [
                { doc-name: "Closure", rarity: "42★", character-avatar: @image-url("images/D32_Steel.png") },
                { doc-name: "Closure", rarity: "42★", character-avatar: @image-url("images/D32_Steel.png") },
                { doc-name: "Closure", rarity: "42★", character-avatar: @image-url("images/D32_Steel.png") },
            ]
        }
    ];
}