export enum WebViewType {
    MicrosoftEdgeWebView2
}

export enum ReleaseUpdateType {
    Delta,
    FullDownload
}

export enum ReleaseUpdateState { 
    Idle,
    Downloading,
    Ready
}

export global StateGlobals {
    in-out property <WebViewType> default-webview-installation-type;
    in-out property <bool> has-default-webview-installation;
    in-out property <bool> has-webview-launch-failure;

    in-out property <string> site-announcement: "";
    in-out property <bool> is-site-under-maintenance: false;

    in-out property <string> update-version;
    in-out property <ReleaseUpdateType> update-type;
    in-out property <string> update-size;
    in-out property <string> update-downloaded-size;
    in-out property <float> update-progress;
    in-out property <bool> update-indeterminate;
    in-out property <ReleaseUpdateState> update-state;
}
